DROP TABLE IF EXISTS atividades;
DROP TABLE IF EXISTS alunos;
DROP TABLE IF EXISTS alunos_pendentes;
DROP TABLE IF EXISTS professores;

CREATE TABLE IF NOT EXISTS alunos(
	id SERIAL NOT NULL,
	nome VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL,
	senha VARCHAR(50) NOT NULL,
	matricula VARCHAR(50) NOT NULL,
	curso VARCHAR(100) NOT NULL,
	usertoken VARCHAR(100) NOT NULL UNIQUE,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS alunos_pendentes(
	id SERIAL NOT NULL,
	nome VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL,
	senha VARCHAR(50) NOT NULL,
	matricula VARCHAR(50) NOT NULL,
	curso VARCHAR(100) NOT NULL,
	usertoken VARCHAR(100) NOT NULL UNIQUE,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS atividades(
	id SERIAL NOT NULL,
	titulo VARCHAR(200) NOT NULL,
	data_inicio VARCHAR(50) NOT NULL,
	data_fim VARCHAR(50) NOT NULL,
	categoria VARCHAR(10) NOT NULL,
	sub_categoria VARCHAR(10) NOT NULL,
	descricao VARCHAR(5000) NOT NULL,
	quantidade_horas VARCHAR(10) NOT NULL,
	usertoken VARCHAR(100) NOT NULL,
	doc_link VARCHAR(1000),
	nome_pdf VARCHAR(1000),
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (usertoken) REFERENCES alunos (usertoken)
);

CREATE TABLE IF NOT EXISTS professores(
	id SERIAL NOT NULL,
	nome VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL,
	senha VARCHAR(50) NOT NULL,
	matricula VARCHAR(50) NOT NULL,
	usertoken VARCHAR(100) NOT NULL UNIQUE,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS admins(
	id SERIAL NOT NULL,
	email VARCHAR(200) NOT NULL,
	senha VARCHAR(50) NOT NULL,
	usertoken VARCHAR(100) NOT NULL UNIQUE,
	ativo BOOLEAN NOT NULL DEFAULT TRUE,
	data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);